### ISSUE TITLE
Machine Learning (Kaggle Learn)

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#112]
- https://www.kaggle.com/vochicong/eda-house-prices-advanced/edit
- https://www.kaggle.com/learn/machine-learning

### Level 1
- [x] 1. How Models Work
- [x] 2. Explore Your Data
- [x] 3. Exercise: Explore Your Data
- [x] 4. Your First Machine Learning Model
- [x] 5. Exercise: Your First Machine Learning Model
- [x] 6. Model Validation
- [x] 7. Exercise: Model Validation
- [x] 8. Underfitting and Overfitting
- [x] 9. Exercise: Underfitting and Overfitting
- [x] 10. Random Forests
- [x] 11. Exercise: Random Forests
- [x] 12. Exercise: Machine Learning Competitions

### Level 2
- [x] 1. Handling Missing Values
- [x] 2. Using Categorical Data with One Hot Encoding
- [x] 3. XGBoost #119
- [x] 4. Partial Dependence Plots
- [x] 5. Pipelines
- [x] 6. Cross-Validation
- [ ] 7. Data Leakage

**Comment by vochicong** [comment]
Kaggle の Learn シリーズは、説明がわかりやすく、サンプルコードをすぐに実行できて、エクササイズも正解かチェックされるので、進めやすいです。

もしかして最初の入門は Kaggle の Learn シリーズが最適かもしれませんね。
