### ISSUE TITLE
House Prices: Advanced Regression Techniques (Competition)

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#119]
# Refs

- [Leaderboard](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/leaderboard)
- [Dataset](https://web.kamihq.com/web/viewer.html?state=%7B%22ids%22%3A%5B%221V_ZwjdbM_h68rkGdeknnRFYtXQEWC9bd%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22103352936481849984502%22%7D&filename=decock.pdf)
- [Data documentation](https://ww2.amstat.org/publications/jse/v19n3/decock/DataDocumentation.txt)

# Tasks
- [x] Impute missing values
- [x] Mark missing values imputed
- [x] RandomForest
- [x] XGBoost
- [x]  Don't reuse variable names!
- [x] Log target
- [x] Normalize predictors
- [x]  Categorical (Ordinal/Nominal) feature
- [ ] careful feature engineering
- [ ] refactoring to methods and classes

**Comment by vochicong** [comment]
The data has 82 columns which include 23 nominal, 23 ordinal, 14 discrete, and 20 continuous variables
