### ISSUE TITLE
prepare for ML job

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#123]
## Prepare for Machine Learning job

- [x]  [Deep Learning with Python](https://www.safaribooksonline.com/library/view/deep-learning-with/9781617294433/) :book: by François Chollet :star::star::star::star:
- [x]  [Deep Learning](https://www.coursera.org/account/accomplishments/specialization/Z23QYSJ94QTU) :tv:, a 5-course specialization by [deeplearning.ai](http://deeplearning.ai/) :star::star::star::star:
- [x]  Kaggle Pandas & Data visualisation course #107
- [x]  [Production Machine Learning Systems by Google on Coursera](https://www.coursera.org/learn/gcp-production-ml-systems) #111
- [x]  [Data Engineering Quest](https://qwiklabs.com/quests/25) :tv: Qwiklabs, 7h #126
- [x] Machine Learning APIs Quest #135
- [ ]  Machine Learning with TensorFlow on Google Cloud Platform Specialization #134
- [ ]  Advanced Machine Learning with TensorFlow on Google Cloud Platform Coursera Specialization #131
- [ ]  [Google Cloud Certified Professional Data Engineer](https://cloud.google.com/certification/data-engineer) :ticket:
- [ ]  [Data Engineering on Google Cloud Platform](https://www.coursera.org/specializations/gcp-data-machine-learning) :tv: Coursera
- [ ]  [Data Science on the Google Cloud Platform](https://www.safaribooksonline.com/library/view/data-science-on/9781491974551/) :book: by Valliappa Lakshmanan #51
- [ ]  [Hands-On Machine Learning with Scikit-Learn and TensorFlow](https://www.safaribooksonline.com/library/view/hands-on-machine-learning/9781491962282/) :book: by Aurélien Géron #124
- [ ]  AWS Certified Big Data - Specialty :ticket:
- [ ]  [AWS Big Data Technology Fundamentals](https://www.aws.training/transcript/curriculumplayer?transcriptId=tFJXk7lv8k6Bh3oyLkiuTA2) :ticket:
- [ ]  [Learn SQL and BigQuery](https://www.kaggle.com/learn/sql) on Kaggle, using Python
