### ISSUE TITLE
Advanced Machine Learning with TensorFlow on Google Cloud Platform Coursera Specialization 

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#131]
[https://www.coursera.org/specializations/advanced-machine-learning-tensorflow-gcp](https://www.coursera.org/specializations/advanced-machine-learning-tensorflow-gcp)
1ヶ月無料キャンペーン中
Start this Specialization & your first month of learning is free. See More Offers

その他の Google コースのキャンペーン
[https://www.coursera.org/promo/NEXTExtended](https://www.coursera.org/promo/NEXTExtended)

- [x]  End-to-End Machine Learning with TensorFlow on GCP, 
3 weeks of study, 8 - 10 hours per week
- [x]  Production Machine Learning Systems #111, 2 weeks, 
5 - 7 hours per week
- [x]  Image Understanding with TensorFlow on GCP, 2 weeks, 
5 - 7 hours per week
- [x]  Sequence Models for Time Series and Natural Language Processing, 2 weeks
- [x]  Recommendation Systems with TensorFlow on GCP (unknown required work amount)
