### ISSUE TITLE
TensorFlow in Practice Specialization

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#179]
[TensorFlow in Practice Specialization](https://www.coursera.org/specializations/tensorflow-in-practice)は[Deep Learning Specialization](https://www.coursera.org/specializations/deep-learning)よりもツールに重きを置くが、基本的な概念も平易な言葉で説明しています。

Deep Learning Specializationがより深掘りして、基本をしっかり説いています。ただし、結局演習では NumPy や Keras を多用するので、ツールに慣れていないと、焦ったり疲弊したりしかねない。

もしかして、TensorFlow in Practice Specializationを先にやって、ツールになれつつ、概要も俯瞰してから深掘りのDeep Learning Specializationに取り掛かったほうが効率的かもしれない。

- [x] [Introduction to TensorFlow for Artificial Intelligence, Machine Learning, and Deep Learning](https://www.coursera.org/learn/introduction-tensorflow)
- [x] [Convolutional Neural Networks in TensorFlow](https://www.coursera.org/learn/convolutional-neural-networks-tensorflow)
- [x] [Natural Language Processing in TensorFlow](https://www.coursera.org/learn/natural-language-processing-tensorflow)
- [x] [Sequences, Time Series and Prediction](https://www.coursera.org/learn/tensorflow-sequences-time-series-and-prediction)

**Comment by vochicong** [comment]
実際、TensorFlow in Practice Specializationの中で、講師（Laurence Moroneyさん）がよくDeep Learning Specializationへの参照を促す。
