### ISSUE TITLE
GCP Big Data and ML Fundamentals Coursera

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#63]
[Google Cloud Platform Big Data and Machine Learning Fundamentals](https://www.coursera.org/learn/gcp-big-data-ml-fundamentals) :tv: on  Coursera

- [ ] Module 1: Introduction to Google Cloud Platform and its Big Data Products
- [ ] Module 2: Foundations of GCP Compute and Storage
- [ ] Module 3: Data Analysis on the Cloud
- [ ] Module 4: Scaling Data Analysis: Compute with GCP
- [ ] Module 5: Data Processing Architectures: Scalable Ingest, Transform and Load
- [ ] Module 6: Summary of Google Cloud Platform, Big Data, and ML
