### ISSUE TITLE
Study Progress Tracker

### ISSUE THREAD

**Issue by vochicong** [vochicong/progress#99]
# Study Progress Tracker

## Machine Learning

 - [ ] [Google Cloud Certified Professional Data Engineer](https://cloud.google.com/certification/data-engineer) :ticket:
	 - [ ] [Data Engineering](https://qwiklabs.com/quests/25) :tv: Qwiklabs, 7h
 - [ ] [Data Engineering on Google Cloud Platform](https://www.coursera.org/specializations/gcp-data-machine-learning) :tv:  Coursera
 - [ ] [Data Science on the Google Cloud Platform](https://www.safaribooksonline.com/library/view/data-science-on/9781491974551/) :book: by Valliappa Lakshmanan
 - [ ] [Hands-On Machine Learning with Scikit-Learn and TensorFlow](https://www.safaribooksonline.com/library/view/hands-on-machine-learning/9781491962282/) :book: by Aurélien Géron
 - [x] [Deep Learning](https://www.coursera.org/account/accomplishments/specialization/Z23QYSJ94QTU) :tv:, a 5-course specialization by deeplearning.ai :star::star::star::star:
 - [x] [Deep Learning with Python](https://www.safaribooksonline.com/library/view/deep-learning-with/9781617294433/)  :book: by François Chollet :star::star::star::star:

## Big Data

- [ ] AWS Certified Big Data - Specialty  :ticket: 
- [ ] [AWS Big Data Technology Fundamentals](https://www.aws.training/transcript/curriculumplayer?transcriptId=tFJXk7lv8k6Bh3oyLkiuTA2)  :ticket:
- [ ] [Learn SQL and BigQuery](https://www.kaggle.com/learn/sql) on Kaggle, using Python

### [AWS Certification Roadmap](https://aws.amazon.com/certification/#roadmap)

- [ ] AWS Certified Solutions Architect - Associate :ticket:
	- [ ] [Solutions Architect - Associate](https://qwiklabs.com/quests/10) :tv:  Qwiklabs, 4h
	- [ ] [Solutions Architect - Professional](https://qwiklabs.com/quests/11) :tv:  Qwiklabs, 3h
- [ ] AWS Certified DevOps Engineer - Professional :ticket:
	- [ ] AWS Certified Developer - Associate :ticket:
	- [ ] [Developer - Associate](https://qwiklabs.com/quests/20) :tv:  Qwiklabs, 4h

### [AWS Developer Professional Series on edX](https://www.edx.org/aws-developer-professional-series)

 - [ ] Building on AWS: Lambda, Rekognition, SQS
 - [ ] Deploying on AWS: CF, Build, Pipeline, Elasticsearch
 - [ ] Optimizing on AWS: ECS, ElastiCache, CloudTrail, KMS

## PM

 - [x] PMP Certified [1886573](https://www.youracclaim.com/badges/dbebbbb6-c323-4f92-884a-1af0b55f87ad/public_url) :ticket: :star::star::star::star:
 - [ ] PMI-ACP :ticket:
 - [x] [PMI-ACP Exam Prep](https://www.udemy.com/pmiacp_21pdus/learn/v4/t/practice/1023892/introduction) :tv: - 21 PDUs training course by Joseph Phillips on Udemy :star::star::star:
 - [x] [The Agile principles](https://www.safaribooksonline.com/library/view/the-agile-principles/9781492036494/) :book: by Jennifer Greene; Andrew Stellman :star::star::star::star::star:
 - [ ] [Head First  Agile](https://www.safaribooksonline.com/library/view/head-first-agile/9781491944684/) :book: by Jennifer Greene; Andrew Stellman
 - [ ] [Succeeding with Agile](https://www.safaribooksonline.com/library/view/succeeding-with-agile/9780321660534/) :book: by Mike Cohn
 - [x] [PMI-ACP Exam Guidance](https://www.pmi.org/certifications/types/agile-acp/exam-prep) :book: including *PMI-ACP Handbook*, *PMI-ACP Exam Content Outline* and *PMI-ACP Presentation*
 - [ ] [PMBOK Guide](https://www.safaribooksonline.com/library/view/a-guide-to/9781628253900/part01.xhtml) :book: by PMI
 - [ ] [Agile Practice Guide](https://www.safaribooksonline.com/library/view/agile-practice-guide/9781628253993/) :book: by PMI

    
## Tools & Links

- [ZenHub](https://app.zenhub.com/workspace/o/vochicong/progress/reports?report=burndown) to create milestones and burn down charts :star::star::star::star::star:
- [AnkiApp](https://www.ankiapp.com/) to create flashcards :star::star::star::star:
- [PM Webinars](https://www.projectmanagement.com/Webinars/webinarMainOnDemand.cfm) :tv: :star::star::star:
